"""NANDA-native identity layer for MassClaw.

Public surface:

    from app.identity import (
        AgentFacts, AgentFactsBuilder, AgentFactsExtensions,
        Capabilities, CapabilityAuthentication, Certification,
        Endpoints, IntegrityCredential, IntegrityProof,
        Provider, Skill, Telemetry, TelemetryMetrics,
        AgentKeyPair, KeyStore,
        canonicalize, sign_bytes, verify_bytes,
        parse_did, build_did_key, build_did_web, build_did_nanda,
        decode_did_key, decode_did_nanda, did_web_to_url,
        DIDResolver, ResolvedAgent, ResolutionError,
        NandaIndexClient, NandaIndexConfig,
        NandaIndexError, NandaIndexNotFound, NandaIndexUnavailable,
        NandaIndexInvalidResponse, NandaIndexUnauthorized,
        AgentRegistration, RegistrationResult,
        HttpxWellKnownFetcher, WellKnownFetchError,
    )
"""

from __future__ import annotations

from app.identity.agent_facts import (
    INTEGRITY_CRYPTOSUITE,
    INTEGRITY_PROOF_TYPE,
    AgentFacts,
    AgentFactsBuilder,
    AgentFactsExtensions,
    Capabilities,
    CapabilityAuthentication,
    Certification,
    Endpoints,
    IntegrityCredential,
    IntegrityProof,
    Provider,
    Skill,
    Telemetry,
    TelemetryMetrics,
)
from app.identity.canonicalize import canonicalize
from app.identity.did import (
    DID_METHOD,
    DID_METHOD_KEY,
    DID_METHOD_NANDA_LEGACY,
    DID_METHOD_WEB,
    MalformedDIDError,
    build_did_from_public_key,
    build_did_key,
    build_did_nanda,
    build_did_web,
    decode_did_key,
    decode_did_nanda,
    did_web_to_url,
    parse_did,
    public_key_from_did,
)
from app.identity.did_resolver import DIDResolver, ResolutionError, ResolvedAgent
from app.identity.key_store import AgentKeyPair, KeyStore
from app.identity.nanda_index import (
    AgentRegistration,
    NandaIndexClient,
    NandaIndexConfig,
    NandaIndexError,
    NandaIndexInvalidResponse,
    NandaIndexNotFound,
    NandaIndexUnauthorized,
    NandaIndexUnavailable,
    RegistrationResult,
)
from app.identity.signer import (
    KeyPair,
    decode_multibase,
    encode_multibase,
    generate_keypair,
    public_key_multibase,
    sign_bytes,
    verify_bytes,
)
from app.identity.well_known_fetcher import HttpxWellKnownFetcher, WellKnownFetchError

__all__ = [
    "DID_METHOD",
    "DID_METHOD_KEY",
    "DID_METHOD_NANDA_LEGACY",
    "DID_METHOD_WEB",
    "INTEGRITY_CRYPTOSUITE",
    "INTEGRITY_PROOF_TYPE",
    "AgentFacts",
    "AgentFactsBuilder",
    "AgentFactsExtensions",
    "AgentKeyPair",
    "AgentRegistration",
    "Capabilities",
    "CapabilityAuthentication",
    "Certification",
    "DIDResolver",
    "Endpoints",
    "HttpxWellKnownFetcher",
    "IntegrityCredential",
    "IntegrityProof",
    "KeyPair",
    "KeyStore",
    "MalformedDIDError",
    "NandaIndexClient",
    "NandaIndexConfig",
    "NandaIndexError",
    "NandaIndexInvalidResponse",
    "NandaIndexNotFound",
    "NandaIndexUnauthorized",
    "NandaIndexUnavailable",
    "Provider",
    "RegistrationResult",
    "ResolutionError",
    "ResolvedAgent",
    "Skill",
    "Telemetry",
    "TelemetryMetrics",
    "WellKnownFetchError",
    "build_did_from_public_key",
    "build_did_key",
    "build_did_nanda",
    "build_did_web",
    "canonicalize",
    "decode_did_key",
    "decode_did_nanda",
    "decode_multibase",
    "did_web_to_url",
    "encode_multibase",
    "generate_keypair",
    "parse_did",
    "public_key_from_did",
    "public_key_multibase",
    "sign_bytes",
    "verify_bytes",
]
