"""add_intelligence_and_project_tables

Revision ID: 6ae375ab1f61
Revises: de32d0b64c0a
Create Date: 2026-04-13 05:49:21.210920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ae375ab1f61'
down_revision: Union[str, Sequence[str], None] = 'de32d0b64c0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('project_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'active'"), nullable=False),
    sa.Column('owner_id', sa.String(length=255), server_default=sa.text("'default'"), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('project_id', name=op.f('pk_projects'))
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_projects_status'), ['status'], unique=False)

    op.create_table('backlog_tasks',
    sa.Column('backlog_task_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('priority', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('story_points', sa.Integer(), nullable=True),
    sa.Column('labels', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'new'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_backlog_tasks_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('backlog_task_id', name=op.f('pk_backlog_tasks'))
    )
    with op.batch_alter_table('backlog_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backlog_tasks_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_backlog_tasks_status'), ['status'], unique=False)

    op.create_table('reasoning_traces',
    sa.Column('trace_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('iteration', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('phase', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.workflow_id'], name=op.f('fk_reasoning_traces_workflow_id_workflows'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trace_id', name=op.f('pk_reasoning_traces'))
    )
    with op.batch_alter_table('reasoning_traces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reasoning_traces_workflow_id'), ['workflow_id'], unique=False)

    op.create_table('sprints',
    sa.Column('sprint_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'planning'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_sprints_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sprint_id', name=op.f('pk_sprints'))
    )
    with op.batch_alter_table('sprints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sprints_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sprints_status'), ['status'], unique=False)

    op.create_table('sprint_tasks',
    sa.Column('sprint_task_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('sprint_id', sa.UUID(), nullable=False),
    sa.Column('backlog_task_id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'todo'"), nullable=False),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['backlog_task_id'], ['backlog_tasks.backlog_task_id'], name=op.f('fk_sprint_tasks_backlog_task_id_backlog_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.sprint_id'], name=op.f('fk_sprint_tasks_sprint_id_sprints'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.workflow_id'], name=op.f('fk_sprint_tasks_workflow_id_workflows'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('sprint_task_id', name=op.f('pk_sprint_tasks'))
    )
    with op.batch_alter_table('sprint_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sprint_tasks_backlog_task_id'), ['backlog_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sprint_tasks_sprint_id'), ['sprint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sprint_tasks_status'), ['status'], unique=False)

    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('execution_mode', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('goal_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('reasoning_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.drop_column('reasoning_summary')
        batch_op.drop_column('goal_snapshot')
        batch_op.drop_column('execution_mode')

    with op.batch_alter_table('sprint_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sprint_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_sprint_tasks_sprint_id'))
        batch_op.drop_index(batch_op.f('ix_sprint_tasks_backlog_task_id'))

    op.drop_table('sprint_tasks')
    with op.batch_alter_table('sprints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sprints_status'))
        batch_op.drop_index(batch_op.f('ix_sprints_project_id'))

    op.drop_table('sprints')
    with op.batch_alter_table('reasoning_traces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reasoning_traces_workflow_id'))

    op.drop_table('reasoning_traces')
    with op.batch_alter_table('backlog_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backlog_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_backlog_tasks_project_id'))

    op.drop_table('backlog_tasks')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_status'))
        batch_op.drop_index(batch_op.f('ix_projects_name'))

    op.drop_table('projects')
    # ### end Alembic commands ###
