"""index unindexed foreign keys

Every ``agent_id`` foreign key was already indexed; the self-referential and
secondary ones were not. That is a consistent gap rather than seven unrelated
oversights, and it bites on exactly the queries that follow those columns:

- ``memory_records.parent_version_id`` — the version chain walk in
  ``MemoryService.get_memory_versions`` filters on this column in both
  directions, so each hop was a sequential scan of the whole table.
- ``tasks.parent_task_id`` / ``tasks.blocked_by_task_id`` — DAG parent and
  blocker resolution.
- ``trust_events.workflow_id`` / ``trust_events.task_id`` and
  ``agent_scores.workflow_id`` — per-workflow trust and score rollups.
- ``sprint_tasks.workflow_id`` — sprint-to-workflow linkage.

Postgres does not index a foreign key automatically (only the *referenced*
side gets one, via the primary key or unique constraint), so an unindexed FK
also makes the parent's ``ON DELETE SET NULL`` scan the child table.

Revision ID: 6e91698ee915
Revises: c8e4a91d2f70
Create Date: 2026-08-12 20:54:23.095790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e91698ee915'
down_revision: Union[str, Sequence[str], None] = 'c8e4a91d2f70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_scores_workflow_id'), ['workflow_id'], unique=False)

    with op.batch_alter_table('memory_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memory_records_parent_version_id'), ['parent_version_id'], unique=False)

    with op.batch_alter_table('sprint_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sprint_tasks_workflow_id'), ['workflow_id'], unique=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_blocked_by_task_id'), ['blocked_by_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_parent_task_id'), ['parent_task_id'], unique=False)

    with op.batch_alter_table('trust_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trust_events_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trust_events_workflow_id'), ['workflow_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trust_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trust_events_workflow_id'))
        batch_op.drop_index(batch_op.f('ix_trust_events_task_id'))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_parent_task_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_blocked_by_task_id'))

    with op.batch_alter_table('sprint_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sprint_tasks_workflow_id'))

    with op.batch_alter_table('memory_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memory_records_parent_version_id'))

    with op.batch_alter_table('agent_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_scores_workflow_id'))

    # ### end Alembic commands ###
