"""add_task_tests_table

Revision ID: de32d0b64c0a
Revises: eaf08d20659c
Create Date: 2026-04-13 05:42:47.407501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de32d0b64c0a'
down_revision: Union[str, Sequence[str], None] = 'eaf08d20659c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_tests',
    sa.Column('test_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('test_name', sa.String(length=255), nullable=False),
    sa.Column('test_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assertion', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actual_value', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('execution_time_ms', sa.Float(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], name=op.f('fk_task_tests_task_id_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('test_id', name=op.f('pk_task_tests'))
    )
    with op.batch_alter_table('task_tests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_tests_task_id'), ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_tests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_tests_task_id'))

    op.drop_table('task_tests')
    # ### end Alembic commands ###
