"""add_todo_blocked_status_and_task_blocked_fields

Revision ID: eaf08d20659c
Revises: ff2aa7bae3e4
Create Date: 2026-04-13 05:34:03.613556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaf08d20659c'
down_revision: Union[str, Sequence[str], None] = 'ff2aa7bae3e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add new enum values to taskstatus PostgreSQL enum
    op.execute("ALTER TYPE taskstatus ADD VALUE IF NOT EXISTS 'todo'")
    op.execute("ALTER TYPE taskstatus ADD VALUE IF NOT EXISTS 'blocked'")

    # Add new columns to tasks table
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blocked_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('blocked_by_task_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_tasks_blocked_by_task_id_tasks'), 'tasks', ['blocked_by_task_id'], ['task_id'], ondelete='SET NULL')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tasks_blocked_by_task_id_tasks'), type_='foreignkey')
        batch_op.drop_column('blocked_by_task_id')
        batch_op.drop_column('blocked_reason')

    # ### end Alembic commands ###
