"""initial_schema

Revision ID: ff2aa7bae3e4
Revises: 
Create Date: 2026-04-13 01:14:07.376060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'ff2aa7bae3e4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Required PostgreSQL extensions
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('agent_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('endpoint', sa.String(length=2048), nullable=False),
    sa.Column('supported_tools', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('cost_profile', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('latency_profile', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('trust_score', sa.Float(), server_default=sa.text('0.5'), nullable=False),
    sa.Column('version', sa.String(length=50), server_default=sa.text("'1.0.0'"), nullable=False),
    sa.Column('safety_level', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'suspended', 'degraded', name='agentstatus'), server_default=sa.text("'active'"), nullable=False),
    sa.Column('health_check_url', sa.String(length=2048), nullable=True),
    sa.Column('last_health_check', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('agent_id', name=op.f('pk_agents'))
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_index('ix_agents_capabilities_gin', ['capabilities'], unique=False, postgresql_using='gin')
        batch_op.create_index(batch_op.f('ix_agents_name'), ['name'], unique=True)
        batch_op.create_index('ix_agents_name_trgm', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
        batch_op.create_index(batch_op.f('ix_agents_status'), ['status'], unique=False)
        batch_op.create_index('ix_agents_status_trust', ['status', sa.literal_column('trust_score DESC')], unique=False)

    op.create_table('policy_rules',
    sa.Column('rule_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rule_type', sa.Enum('content', 'access', 'resource', 'workflow', name='policyruletype'), nullable=False),
    sa.Column('condition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('action', sa.Enum('allow', 'deny', 'require_approval', 'flag', 'log', name='policyaction'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('rule_id', name=op.f('pk_policy_rules'))
    )
    with op.batch_alter_table('policy_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policy_rules_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_policy_rules_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_rules_rule_type'), ['rule_type'], unique=False)

    op.create_table('workflows',
    sa.Column('workflow_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('pending', 'decomposing', 'running', 'paused', 'completed', 'failed', 'cancelled', name='workflowstatus'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('budget_limit', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('budget_used', sa.Numeric(precision=12, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('priority', sa.Integer(), server_default=sa.text('5'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('dag_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('workflow_id', name=op.f('pk_workflows'))
    )
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflows_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflows_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflows_user_id'), ['user_id'], unique=False)

    op.create_table('agent_scores',
    sa.Column('score_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=True),
    sa.Column('quality', sa.Float(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=False),
    sa.Column('cost_efficiency', sa.Float(), nullable=False),
    sa.Column('consistency', sa.Float(), nullable=False),
    sa.Column('reliability', sa.Float(), nullable=False),
    sa.Column('composite', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], name=op.f('fk_agent_scores_agent_id_agents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.workflow_id'], name=op.f('fk_agent_scores_workflow_id_workflows'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('score_id', name=op.f('pk_agent_scores'))
    )
    with op.batch_alter_table('agent_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_scores_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_scores_created_at'), ['created_at'], unique=False)

    op.create_table('memory_records',
    sa.Column('memory_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('source_agent_id', sa.UUID(), nullable=True),
    sa.Column('memory_type', sa.Enum('fact', 'context', 'result', 'reasoning', 'meta', name='memorytype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('confidence', sa.Float(), server_default=sa.text('0.8'), nullable=False),
    sa.Column('freshness', sa.Float(), server_default=sa.text('1.0'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('parent_version_id', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_version_id'], ['memory_records.memory_id'], name=op.f('fk_memory_records_parent_version_id_memory_records'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_agent_id'], ['agents.agent_id'], name=op.f('fk_memory_records_source_agent_id_agents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.workflow_id'], name=op.f('fk_memory_records_workflow_id_workflows'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('memory_id', name=op.f('pk_memory_records'))
    )
    with op.batch_alter_table('memory_records', schema=None) as batch_op:
        batch_op.create_index('ix_memory_records_embedding_ivfflat', ['embedding'], unique=False, postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})
        batch_op.create_index(batch_op.f('ix_memory_records_memory_type'), ['memory_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_records_source_agent_id'), ['source_agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_records_workflow_id'), ['workflow_id'], unique=False)

    op.create_table('tasks',
    sa.Column('task_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('parent_task_id', sa.UUID(), nullable=True),
    sa.Column('assigned_agent_id', sa.UUID(), nullable=True),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('capability', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'assigned', 'running', 'retrying', 'completed', 'failed', 'skipped', name='taskstatus'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('max_retries', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('cost_used', sa.Numeric(precision=12, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['agents.agent_id'], name=op.f('fk_tasks_assigned_agent_id_agents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.task_id'], name=op.f('fk_tasks_parent_task_id_tasks'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.workflow_id'], name=op.f('fk_tasks_workflow_id_workflows'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', name=op.f('pk_tasks'))
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_assigned_agent_id'), ['assigned_agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_capability'), ['capability'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_workflow_id'), ['workflow_id'], unique=False)

    op.create_table('wallet_events',
    sa.Column('wallet_event_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.Enum('credit', 'debit', 'reserve', 'release', name='walletactiontype'), nullable=False),
    sa.Column('credit_delta', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], name=op.f('fk_wallet_events_agent_id_agents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.workflow_id'], name=op.f('fk_wallet_events_workflow_id_workflows'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('wallet_event_id', name=op.f('pk_wallet_events'))
    )
    with op.batch_alter_table('wallet_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wallet_events_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallet_events_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallet_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallet_events_workflow_id'), ['workflow_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('log_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=True),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.Enum('workflow.created', 'workflow.started', 'workflow.completed', 'workflow.failed', 'workflow.cancelled', 'workflow.paused', 'workflow.resumed', 'task.created', 'task.assigned', 'task.started', 'task.completed', 'task.failed', 'task.retried', 'task.skipped', 'agent.registered', 'agent.updated', 'agent.deactivated', 'agent.health_changed', 'trust.updated', 'trust.decayed', 'memory.written', 'memory.queried', 'memory.deleted', 'memory.gc', 'wallet.charged', 'wallet.reserved', 'wallet.released', 'wallet.credited', 'policy.evaluated', 'policy.violation', 'policy.rule_created', 'policy.rule_updated', 'approval.requested', 'approval.granted', 'approval.denied', 'approval.expired', 'agent.promoted', 'agent.demoted', 'score.recorded', 'consensus.requested', 'consensus.reached', 'consensus.failed', name='auditeventtype'), nullable=False),
    sa.Column('actor_type', sa.Enum('system', 'agent', 'user', 'policy', name='actortype'), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=False),
    sa.Column('input_summary', sa.Text(), nullable=True),
    sa.Column('output_summary', sa.Text(), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], name=op.f('fk_audit_logs_task_id_tasks'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.workflow_id'], name=op.f('fk_audit_logs_workflow_id_workflows'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('log_id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_type'), ['actor_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_event_type'), ['event_type'], unique=False)
        batch_op.create_index('ix_audit_logs_input_summary_trgm', ['input_summary'], unique=False, postgresql_using='gin', postgresql_ops={'input_summary': 'gin_trgm_ops'})
        batch_op.create_index('ix_audit_logs_output_summary_trgm', ['output_summary'], unique=False, postgresql_using='gin', postgresql_ops={'output_summary': 'gin_trgm_ops'})
        batch_op.create_index(batch_op.f('ix_audit_logs_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_workflow_id'), ['workflow_id'], unique=False)

    op.create_table('trust_events',
    sa.Column('trust_event_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=True),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('latency_score', sa.Float(), nullable=False),
    sa.Column('cost_score', sa.Float(), nullable=False),
    sa.Column('consistency_score', sa.Float(), nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('old_trust', sa.Float(), nullable=False),
    sa.Column('new_trust', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], name=op.f('fk_trust_events_agent_id_agents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], name=op.f('fk_trust_events_task_id_tasks'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.workflow_id'], name=op.f('fk_trust_events_workflow_id_workflows'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('trust_event_id', name=op.f('pk_trust_events'))
    )
    with op.batch_alter_table('trust_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trust_events_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trust_events_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trust_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trust_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_trust_events_agent_id'))

    op.drop_table('trust_events')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_workflow_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_task_id'))
        batch_op.drop_index('ix_audit_logs_output_summary_trgm', postgresql_using='gin', postgresql_ops={'output_summary': 'gin_trgm_ops'})
        batch_op.drop_index('ix_audit_logs_input_summary_trgm', postgresql_using='gin', postgresql_ops={'input_summary': 'gin_trgm_ops'})
        batch_op.drop_index(batch_op.f('ix_audit_logs_event_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('wallet_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wallet_events_workflow_id'))
        batch_op.drop_index(batch_op.f('ix_wallet_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_wallet_events_agent_id'))
        batch_op.drop_index(batch_op.f('ix_wallet_events_action_type'))

    op.drop_table('wallet_events')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_workflow_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_tasks_capability'))
        batch_op.drop_index(batch_op.f('ix_tasks_assigned_agent_id'))

    op.drop_table('tasks')
    with op.batch_alter_table('memory_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memory_records_workflow_id'))
        batch_op.drop_index(batch_op.f('ix_memory_records_source_agent_id'))
        batch_op.drop_index(batch_op.f('ix_memory_records_memory_type'))
        batch_op.drop_index('ix_memory_records_embedding_ivfflat', postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})

    op.drop_table('memory_records')
    with op.batch_alter_table('agent_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_scores_created_at'))
        batch_op.drop_index(batch_op.f('ix_agent_scores_agent_id'))

    op.drop_table('agent_scores')
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflows_user_id'))
        batch_op.drop_index(batch_op.f('ix_workflows_status'))
        batch_op.drop_index(batch_op.f('ix_workflows_domain'))

    op.drop_table('workflows')
    with op.batch_alter_table('policy_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_rules_rule_type'))
        batch_op.drop_index(batch_op.f('ix_policy_rules_priority'))
        batch_op.drop_index(batch_op.f('ix_policy_rules_name'))

    op.drop_table('policy_rules')
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index('ix_agents_status_trust')
        batch_op.drop_index(batch_op.f('ix_agents_status'))
        batch_op.drop_index('ix_agents_name_trgm', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
        batch_op.drop_index(batch_op.f('ix_agents_name'))
        batch_op.drop_index('ix_agents_capabilities_gin', postgresql_using='gin')

    op.drop_table('agents')

    # Drop extensions
    op.execute("DROP EXTENSION IF EXISTS vector")
    op.execute("DROP EXTENSION IF EXISTS pg_trgm")
    # ### end Alembic commands ###
